# Generated by Django 5.0.7 on 2024-08-03 15:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_id', models.CharField(max_length=50)),
                ('selfLink', models.CharField(max_length=200, verbose_name='link')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('authors', models.CharField(max_length=250, verbose_name='Autores')),
                ('publisher', models.CharField(max_length=250, verbose_name='Editora')),
                ('publishedDate', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('industryIdentifiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='Identifier')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='Categorias')),
                ('thumbnail', models.CharField(max_length=250, verbose_name='Thumbnail')),
                ('image', models.CharField(max_length=250, verbose_name='Imagem')),
                ('language', models.CharField(max_length=250, verbose_name='Idioma')),
                ('pais', models.CharField(max_length=250, verbose_name='Paś')),
                ('country', models.CharField(max_length=250, verbose_name='País')),
                ('page_count', models.CharField(max_length=250, verbose_name='pageCount')),
            ],
        ),
        migrations.CreateModel(
            name='MeuCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livro', verbose_name='Conta')),
            ],
        ),
    ]
