# Generated by Django 5.0.7 on 2024-08-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeuCarrinho',
            new_name='Carrinho',
        ),
    ]
