# Generated by Django 5.0.7 on 2024-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_meucarrinho_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livro',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='livro_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='selfLink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
