# Generated by Django 5.0.7 on 2024-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_carrinho_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do item'),
        ),
    ]
