# Generated by Django 5.0.7 on 2024-08-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carrinho_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
